CREATE TABLE UniversityProfiles
(
    UniversityId INT PRIMARY KEY IDENTITY(1,1),

    UniversityName VARCHAR(200),
    ShortName VARCHAR(50),
    UniversityCode VARCHAR(50),
    UniversityTypeId INT NULL,
    EstablishedYear INT NULL,
    Accreditation VARCHAR(250),
    Website VARCHAR(200),
    Email VARCHAR(150),
    Phone VARCHAR(50),
    TaxNumber VARCHAR(100),
    AffiliatedUniversity VARCHAR(200),
    IsActive BIT,

    Motto VARCHAR(250),
    Vision VARCHAR(500),
    Mission VARCHAR(1000),
    Description VARCHAR(2000),
    AboutUniversity VARCHAR(4000),
    RegistrationNumber VARCHAR(100),
    UGCApprovalNumber VARCHAR(100),
    AICTEApproval VARCHAR(100),
    NAACGrade VARCHAR(20),
    NIRFRank VARCHAR(20),
    ISOCertification VARCHAR(100),
    OfficeNumber VARCHAR(50),
    FaxNumber VARCHAR(50),
    DetailsEmail VARCHAR(150),
    DetailsWebsite VARCHAR(200),
    Facebook VARCHAR(250),
    LinkedIn VARCHAR(250),
    Instagram VARCHAR(250),
    Twitter VARCHAR(250),

    LogoMainPath VARCHAR(300),
    LogoDarkPath VARCHAR(300),
    LogoLightPath VARCHAR(300),
    LogoSidebarPath VARCHAR(300),
    FaviconPath VARCHAR(300),

    Country VARCHAR(100),
    State VARCHAR(100),
    District VARCHAR(100),
    City VARCHAR(100),
    Area VARCHAR(150),
    Street VARCHAR(200),
    BuildingNumber VARCHAR(50),
    PostalCode VARCHAR(20),
    Latitude VARCHAR(30),
    Longitude VARCHAR(30),

    ContOffice VARCHAR(50),
    ContMobile VARCHAR(50),
    ContAlternate VARCHAR(50),
    ContAdmissionHelpline VARCHAR(50),
    ContRegistrarOffice VARCHAR(50),
    ContEmail VARCHAR(150),
    ContSupportEmail VARCHAR(150),
    ContWebsite VARCHAR(200),

    CreatedDate DATETIME,
    UpdatedDate DATETIME
)
